server:
  servlet:
      context-path: /pmanager
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null  #isso aqui é para remover da requisição de valores nulos.
  application:
    name: pmanager
  datasource:
    url: jdbc:h2:mem:teste
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true